language: node_js
os:
  - windows
  - linux
  - osx
node_js:
  - 6
  - 8
  - 10
  - "node"

env:
  global:
    COVERALLS_PARALLEL: true

before_install:
  - npm cache clear --force

after_success: nyc report --reporter=text-lcov | coveralls
